version: '3.8'

# sudo docker-compose down -v && sudo docker-compose -p modulith up --build

services:
  catalog.db:
    image: postgres
    container_name: catalog.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogdb
      restart: always
    ports:
      - "5441:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

volumes:
  postgres_catalog: