version: '3.8'

# sudo docker-compose down -v && sudo docker-compose -p modulith up --build

services:
  eshop.db:
    image: postgres
    container_name: eshop.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eshop.db
      # restart: always
    ports:
      - "5441:5432"
    volumes:
      - postgres_eshop:/var/lib/postgresql/data
  
  distributedcache:
    image: redis
    container_name: distributedcache
    # restart: always
    ports:
      - "6379:6379"
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    #restart: always
    ports:
      # seq icin
      - "5341:5341"
      # seq dashboard
      - "9091:80"
  
  messagebus:
    image: rabbitmq:management
    container_name: messagebus
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    #restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  identity:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://eshop.db/eshop.db?currentSchema=identity
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      # container name
      - KC_HOSTNAME=http://identity:9090/
      - KC_HTTP_PORT=9090
    #restart: always
    ports:
      - "9090:9090"
    command:
      - start-dev
  
  api:
    container_name: api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ## docker iletisim icin asil port verilir -- ayrica localhostlar container name ile degisilir
      ConnectionStrings__Database: "Server=eshop.db;Port=5432;Database=eshop.db;User Id=postgres;Password=postgres"
      ConnectionStrings__Redis: "distributedcache:6379"
      MessageBroker__Host: "amqp://ecommerce-mq:5672"
      MessageBroker__UserName: guest
      MessageBroker__Password: guest
      Keycloak__AuthServerUrl: http://identity:9090/
      Serilog__Using__0: Serilog.Sinks.Console
      Serilog__Using__1: Serilog.Sinks.Seq
      Serilog__MinimumLevel__Default: Information
      Serilog__MinimumLevel__Override__Microsoft: Information
      Serilog__MinimumLevel__Override__System: Warning
      Serilog__WriteTo__0__Name: Console
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__serverUrl: http://seq:5341
      Serilog__Enrich__0: FromLogContext
      Serilog__Enrich__1: WithMachineName
      Serilog__Enrich__2: WithProcessId
      Serilog__Enrich__3: WithThreadId
      Serilog__Properties__Application: "EShop ASP.NET Core App"
      Serilog__Properties__Environment: Development
    depends_on:
      - eshop.db
      - distributedcache
      - seq
      - messagebus
      - identity
    ports:
      - "6000:8080"
      #- "6060:8081"

volumes:
  postgres_eshop:
  
