version: '3.8'

# sudo docker-compose down -v && sudo docker-compose -p modulith up --build

services:
  eshop.db:
    image: postgres
    container_name: eshop.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eshop.db
      # restart: always
    ports:
      - "5441:5432"
    volumes:
      - postgres_eshop:/var/lib/postgresql/data
  
  distributedcache:
    image: redis
    container_name: distributedcache
    # restart: always
    ports:
      - "6379:6379"
    
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    #restart: always
    ports:
      # seq icin
      - "5341:5341"
      # seq dashboard
      - "9091:80"
  
  messagebus:
    image: rabbitmq:management
    container_name: messagebus
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    #restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  identity:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://eshop.db/eshop.db?currentSchema=identity
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      #- KC_HOSTNAME=http://identity:9090/
      #- KC_HTTP_PORT=9090
    #restart: always
    ports:
      - "9090:8080"
    command:
      - start-dev

volumes:
  postgres_eshop: