version: '3.8'

# sudo docker-compose down -v && sudo docker-compose -p modulith up --build

services:
  eshop.db:
    image: postgres
    container_name: eshop.db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eshop.db
      restart: always
    ports:
      - "5441:5432"
    volumes:
      - postgres_eshop:/var/lib/postgresql/data

volumes:
  postgres_eshop: